output_folder = "d:/streams"
log_format = "{time} | {level} | {name}:{function}:{line} | {extra[streamer]} | {message}"

channel_ids = [
    "UCUyeluBRhGPCW4rPe_UvBZQ",
    "UC1E-JS8L0j1Ei70D9VEFrPQ",
    # "UCI_mwTKUhicNzFrhm33MzBQ"
]
