output_folder = "d:/streams"
log_format = "<green>{time}</green> | <level>{level}</level> | <cyan>{name}:{function}:{line}</cyan> | <magenta>{extra[streamer]}</magenta> | <level>{message}</level>"

channel_ids = [
    "UCUyeluBRhGPCW4rPe_UvBZQ",
    "UC1E-JS8L0j1Ei70D9VEFrPQ",
    # "UCI_mwTKUhicNzFrhm33MzBQ"
]
