output_folder = "d:/streams"
log_format = "<green>{time}</green> | <level>{level:<5}</level> | <cyan>{name}:{function}:{line:<4}</cyan> | <magenta>{extra[streamer]:<15}</magenta> | <level>{message}</level>"

[[channels]]
id = "UCUyeluBRhGPCW4rPe_UvBZQ"
mode = "youtube_live"

[[channels]]
id = "UC1E-JS8L0j1Ei70D9VEFrPQ"
mode = "youtube_live"

[[channels]]
id = "UCaTznQhurW5AaiYPbhEA-KA"
mode = "youtube_live"

[[channels]]
id = "joshstrifehayes"
mode = "twitch"

# [[channels]]
# id = "UCI_mwTKUhicNzFrhm33MzBQ"
# mode = "youtube_live"
