worker_processes 1;

error_log  nginx/nginx.log;
pid        nginx/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       C:/tools/nginx-1.29.7/conf/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    access_log    nginx/nginx.log;
    client_body_temp_path  nginx/temp/client_body;
    proxy_temp_path        nginx/temp/proxy;
    fastcgi_temp_path      nginx/temp/fastcgi;
    uwsgi_temp_path        nginx/temp/uwsgi;
    scgi_temp_path         nginx/temp/scgi;

    server {
        listen 80;
        root dist;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
